---
- hosts: all
  become: yes
  gather_facts: yes

  environment:
    http_proxy: http://192.168.1.3:54225 
    https_proxy: http://192.168.1.3:54225
    no_proxy: localhost,127.0.0.0,127.0.1.1,127.0.1.1,local.home

  # 设置环境变量
  #- name: populate /etc/environment
    #lineinfile:
    #  path: "/etc/environment"
    #  regexp: "^{{ item.key }}="
    #  line: "{{ item.key }}={{ item.value}}"
    #  state: present
    #with_items: "{{ os_environment }}"

  pre_tasks:
    - name: Ensure Ansible dependencies are installed (CentOS 6).
      yum:
        name: libselinux-python
        state: present
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version | int == 6

  roles:
    - role: geerlingguy.nfs

    - role: geerlingguy.packer_rhel
      when: ansible_os_family == 'RedHat'

    - role: geerlingguy.packer-debian
      when: ansible_os_family == 'Debian'

  tasks:
    - name: Install some helpful utilities.
      apt:
        name:
          - git
          - wget
          - curl
          - vim
        state: present
      when: ansible_os_family == 'Debian'
